Repository AlaskaAirlines/WC-Generator, pull requests merged in 2021-09, with the labels that each got.

#200 refactor(scripts): runs tests before bundler
  template/package.json
Labels: Type: Refactoring, generator

#202 ci(git): deletes branches on merge
  template/.github/settings.yml
Labels: Status: Review Needed, generator

#198 docs(readme): corrects typo in demo build instruction
  template/README.md
Labels: Type: Bug, generator

#204 Chore: dependency update security vulnerabilities
  package-lock.json
  package.json
Labels: Type: Dependencies, Status: Complete

#209 docs(tickets): update publish ticket content
  template/.github/ISSUE_TEMPLATE/publish_component.md
Labels: Type: Documentation, generator

#212 docs(template): add release candidate issue template
  template/.github/ISSUE_TEMPLATE/release_candidate.md
Labels: Type: Documentation, Status: Review Needed, generator

#216 fix(lit): fix generator to use v2.5.1 of LitElement #215
  template/package.json
Labels: Type: Bug, Status: Complete, auro-generator

#221 Address correct versions of node for verification
  .github/workflows/testPublish.yml
  template/.github/workflows/testPublish.yml
  util/verifyNodeVersion.js
Labels: Type: Bug, Status: Review Needed, auro-generator

#223 Update codeowners file to reflect team org updates
  .github/CODEOWNERS
  template/.github/CODEOWNERS
Labels: Type: Bug, Status: Review Needed, Type: CI
