Repository AlaskaAirlines/WC-Generator, pull requests merged in 2021-06, with the labels that each got.

#141 Update settings.yml
  .github/settings.yml
  template/.github/settings.yml
Labels: Status: Complete, Status: Review Needed, Type: Bug

#144 Add gitignore setting; remove label json file
  template/.github/labelSettings.json
  template/.gitignore.temp
Labels: Status: Complete, Status: Review Needed, Type: Bug

#146 fix(husky migration): update scripts to address husky init
  util/auroMigrate.md
  util/auroMigrate.sh
  util/help-outputs.js
Labels: Status: Complete, Status: Review Needed, Type: Bug, Type: Documentation

#148 Add ignored files for demo
  template/.gitignore.temp
Labels: Status: Complete, Status: Review Needed, Type: Bug

#150 generator: replace question with statement
  template/package.json
  template/scripts/pre-commit.js
  template/scripts/pre-commit.sh
Labels: Status: Complete, Status: Review Needed, Type: Bug

#154 Remove local dependency for eslint-plugin-lit
  template/package.json
Labels: Status: Complete, Status: Review Needed, Type: Bug

#158 feat(eslint): broaden eslint coverage
  template/package.json
  template/src/es5.js
Labels: Status: Review Needed, Type: Feature
